### ISSUE TITLE
Deploy to Zeit Now?

### ISSUE THREAD

**Issue by izqui** [aragon/anj.aragon.org#26]
The PR preview feature is so good and Now is crazy fast for statically served content

cc @sohkai

**Comment by izqui** [comment]
It would also remove the need to manually deploy the site

**Comment by sohkai** [comment]
No hard preference, although we have automated gh-pages deployments now so it'd really be for testing PRs.

**Comment by sohkai** [comment]
Closing for now—we can evaluate this later since this is updated less and not _really_ an app.
