### ISSUE TITLE
Uniswap: calculate price based on desired trade rather than current spot price

### ISSUE THREAD

**Issue by sohkai** [aragon/anj.aragon.org#56]
Right now we use `getMarketDetails()`, but we should really be using `getTradeDetails()` to get the `minEth` and `minTokens` parameters, as this takes into account the actual (currently expected) slippage from the amounts the user wants to trade.

On large trades that affect liquidity, the real rate will always be much lower / higher than the spot price given by `getMarketDetails()`.

-------

On inspection, we should actually be using **both** of these, at some point or another, to calculate the slippage. We most likely want another Uniswap hook, that allows us to calculate slippage based on the expected price vs. the current spot price.

On large slippage transactions (anything greater than 5%), we should visually warn the user that their transaction will have a large conversion cost. For now, let's use the same warning component we have, but change the text and the Help text.

**Comment by bingen** [comment]
I think using those functions should work:
https://docs.uniswap.io/smart-contract-api/exchange#gettokentoethinputprice
https://docs.uniswap.io/smart-contract-api/exchange#getethtotokeninputprice

Looking at the code:
https://github.com/Uniswap/contracts-vyper/blob/master/contracts/uniswap_exchange.vy#L432
the function used, `getInputPrice` is the same as in exchange functions.
