### ISSUE TITLE
Converter: add "return back to ANT" link

### ISSUE THREAD

**Issue by sohkai** [aragon/anj.aragon.org#57]
If a user has > 0 ANJ in their wallet, add a link to `https://uniswap.exchange/swap?inputCurrency=0xcD62b1C403fa761BAadFC74C525ce2B51780b184&outputCurrency=0x960b236A07cf122663c4303350609A66A7B288C0`.

**Comment by sohkai** [comment]
We should now update this link to `convert.aragon.org` cc @Evalir.

**Comment by Evalir** [comment]
Due to the site now having links to Uniswap & `convert.aragon.org`, should we close this, or add the information if the slippage is high anyway?

**Comment by sohkai** [comment]
Let's close it!
