### ISSUE TITLE
Wrong error message when not enough balance

### ISSUE THREAD

**Issue by bingen** [aragon/anj.aragon.org#6]
See screenshot:

![Screenshot from 2019-12-25 23-00-38](https://user-images.githubusercontent.com/701095/71547009-72263e00-299b-11ea-9a16-f3e6c213ad11.png)

**Comment by bpierre** [comment]
Fixed in https://github.com/aragon/anj.aragon.org/pull/4/commits/52e1faaf7924b3ef495072acc273608430dee478 (replaced native fields validation by a custom validation)
