### ISSUE TITLE
Stats: Total active ANJ calculation 

### ISSUE THREAD

**Issue by rperez89** [aragon/anj.aragon.org#70]
I noticed that we are doing a sum to calculate the total active anj [here](https://github.com/aragon/anj.aragon.org/blob/79e44d2b29eefeeb50a96c7ad0e9b20815d7e4e7/src/utils.js#L56), but instead of doing that we can directly get it from [this function](https://github.com/aragon/aragon-court/blob/212978ce66c9d8b373809fa5c167b560dbdcd821/contracts/registry/JurorsRegistry.sol#L425) inside the jurorsRegistry module

**Comment by sohkai** [comment]
Closed by #https://github.com/aragon/anj.aragon.org/pull/76.
