### ISSUE TITLE
"Something went wrong" error consistently occurring

### ISSUE THREAD

**Issue by john-light** [aragon/anj.aragon.org#87]
Using MetaMask to convert. Entered `130 ANT` for `12000 ANJ` and when I click the button to convert I get this error every time:

![Screenshot_2020-05-01 Aragon Court](https://user-images.githubusercontent.com/9424721/80819004-2b8f5d00-8ba2-11ea-8aaa-7b14715de4b5.png)

**Comment by Evalir** [comment]
This has been fixed now in the Court backend; it was not a frontend error.
